### ISSUE TITLE
login, signup, discord-serversのstore, updateのバリデーション

### ISSUE THREAD

**Issue by yuuttana1223** [omochi-kcg/kcg-community#22]
## 欲しい機能はなに?
- login, signup時にkcgのメールアドレスでないといけない
- discord-serversのバリデーション

## なぜその機能が欲しい?
- kcgのuser以外入れないようにするため。
- discord-serversのバリデーションが存在しないから。

## 実装方法
例). requestを作成してバリデーションを実装

## 参考資料

**Comment by Stefanperlarsson** [comment]
@yuuttana1223 https://github.com/omochi-kcg/kcg-community/commit/7c44b78a2d6e2244a17ddf620beb06c8a3d656a7　<ー　これでDiscordServersのバリデーションが完成していました。

Loginのバリデーションはもうあるみたいので、作ってません
https://github.com/omochi-kcg/kcg-community/blob/5bb3cba474c23b1c98fca7aa54853a326b7d5a61/app/Http/Controllers/Auth/AuthenticatedSessionController.php#L29
https://github.com/omochi-kcg/kcg-community/blob/5bb3cba474c23b1c98fca7aa54853a326b7d5a61/app/Http/Requests/Auth/LoginRequest.php#L29-L35
