### ISSUE TITLE
トップのデサインをまとめる

### ISSUE THREAD

**Issue by Stefanperlarsson** [omochi-kcg/kcg-community#30]
## 欲しい機能はなに?
- トップのリンクは見られないから、どんなページがあるか分からない。
- 左側と右側のリンクとデサインや色は違う
- アイコンの色

## なぜその機能が欲しい?
- [ ] トップの「contents」の代わりに、リンク直接に並んだらどうですか？
- [ ] 左側と右側のリンクとデサインや色と同じにする
- [ ] アイコンの色はテクストと同じ

## 実装方法
![login](https://user-images.githubusercontent.com/64949611/143394796-ecb3bec0-313f-4760-b966-203bdf15c803.png)

## 参考URL
なし

## 参考資料
なし

**Comment by yuuttana1223** [comment]
終わりました。
