### ISSUE TITLE
sign_up後の遷移先を以前使用していたページに変更

### ISSUE THREAD

**Issue by yuuttana1223** [omochi-kcg/kcg-community#36]
## 欲しい機能はなに?
sign_up後の遷移先を以前使用していたページに変更

## なぜその機能が欲しい?
sign_up後の遷移先がdashboardになっているが、dashboardは仮のページで本来ないページだから。

## 参考資料

**Comment by Stefanperlarsson** [comment]
これはもうOKです。
何もしなくていいです
