### ISSUE TITLE
マイグレーション、モデル、ファクトリーとシーダーを作る

### ISSUE THREAD

**Issue by Stefanperlarsson** [omochi-kcg/kcg-community#5]
**どんな問題のためこのフェアシェアが必要.**
マイグレーションとモデルまだないので、作って欲しい

**フェアシェアを説明して**
- https://laravel.com/docs/8.x/eloquent
- https://laravel.com/docs/8.x/migrations

**その他**
得になし

**Comment by Stefanperlarsson** [comment]
## 作業
- [ ] マイグレーション
- [ ] モデル
- [ ] ファクトリー
- [ ] シーダー

## 環境の変更
次のコマンドをターミナルで実行してください
- `docker exec laravel-app ./artisan migrate`
- `docker exec laravel-app ./artisan db:seed`

**Comment by yuuttana1223** [comment]
モデル名は複数形ではなく単数形だと思う。
✕ Boards → ○Board
✕ Categories → ○Category

**Comment by Stefanperlarsson** [comment]
> モデル名は複数形ではなく単数形だと思う。 ✕ Boards → ○Board ✕ Categories → ○Category

@yuuttana1223 そうですね！書き直しました。
https://github.com/omochi-kcg/kcg-community/commit/300ed87fae7dd7fa53d31dc9ca153b04b81bb954
できるだけテストしていましたが、これで`./artisan db:seed`が動けるので、多分大丈夫だと思います。
