### ISSUE TITLE
ERをアップする

### ISSUE THREAD

**Issue by Stefanperlarsson** [omochi-kcg/kcg-community#6]
**どんな問題のためこのフェアシェアが必要.**
ERが終わったら、ここでアップしてほしい

**フェアシェアを説明して**
コメントでファイルをアップしてほしい

**その他**
これを押すと、ファイルをアップできる
![pic](https://user-images.githubusercontent.com/64949611/140274868-795e7cca-0df8-4bed-acca-74c874fe843b.png)

**Comment by furukawa-y** [comment]
![image](https://user-images.githubusercontent.com/92501137/143351395-fe49fffa-0f2b-453b-8825-9a4268964ef1.png)

**Comment by furukawa-y** [comment]
UPしました
